name: Release

on:
  release:
    types: [published]

jobs:

  bump-version:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Update Version in Files
        run: |
          # Update version in __init__.py
          sed -i -E "s/__version__ = '.*'/__version__ = '${{ github.event.release.tag_name }}'/g" midas_open_parser/__init__.py
        
          # Update version in pyproject.toml
          sed -i -E "s/version = '.*'/version = '${{ github.event.release.tag_name }}'/g" pyproject.toml
    
      - name: Commit Version Update
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Bump version to ${{ github.event.release.tag_name }}"
          branch: ${{ github.head_ref }}
    
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload dist/*

